openapi: '3.0.2'
info:
  title: Hekataios
  version: '1.0'
servers:
  - url: https://api.hekataios.app
paths:
  /locations:
    get:
      description: Get locations
      operationId: queryLocations
      tags:
        - locations
      responses:
        '206':
          description: List of locations
    post:
      description: Add a location
      operationId: addLocation
      tags:
        - locations
      responses:
        '201':
          description: Location added.
  /locations/:locationId:
    parameters:
      - $ref: '#/components/parameters/locationId'
    get:
      description: Get a location.
      operationId: getLocation
      tags:
        - locations
      responses:
        '200':
          description: Location retrieved.
    patch:
      description: Update a location.
      operationId: updateLocation
      tags:
        - locations
      responses:
        '204':
          description: Location updated.
  /events:
    get:
      description: Get events.
      operationId: queryEvents
      tags:
        - events
      responses:
        '206':
          description: List of events.
    post:
      description: Add an event.
      operationId: addEvent
      tags:
        - events
      responses:
        '201':
          description: Event added.
  /events/:eventId:
    parameters:
      - $ref: '#/components/parameters/eventId'
    get:
      description: Get an event.
      operationId: getEvent
      tags:
        - events
      responses:
        '200':
          description: Event retrieved.
    patch:
      description: Update an event.
      operationId: updateEvent
      tags:
        - events
      responses:
        '204':
          description: Event updated.
  /reports:
    get:
      description: Get reports.
      operationId: queryReports
      tags:
        - reports
      responses:
        '206':
          description: List of reports.
    post:
      description: Report a resource.
      operationId: report
      tags:
        - reports
        - events
        - locations
      responses:
        '201':
          description: Resource reported.
components:
  parameters:
    eventId:
      name: eventId
      in: path
      description: The id of the event.
      required: true
      schema:
        type: string
        format: uuid
    locationId:
      name: locationId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: The ID of the location.
